"""
Django settings for robofi project.

Generated by 'django-admin startproject' using Django 3.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import os
import sys
from datetime import timedelta
from pathlib import Path

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

AUTOMATE_PATH = os.path.join(BASE_DIR, "automate")
print(f"AUTOMATE_PATH : {AUTOMATE_PATH}")

sys.path.append(os.path.join(
    AUTOMATE_PATH, "microbots", "python"))

# Application definition
INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'whitenoise.runserver_nostatic',

    'pages.users',
    'pages.users.detail',
    'pages.automation',

    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'robofi.urls'
AUTH_USER_MODEL = 'users.User'
WSGI_APPLICATION = 'robofi.wsgi.application'
ASGI_APPLICATION = 'robofi.asgi.application'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'static', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

USE_TZ = True
USE_I18N = True
USE_L10N = True
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'

# Setting Environment variables

if (os.path.exists(os.path.join(Path(__file__).resolve().parent, 'environment.py'))):
    from .environment import environment
else:
    environment = os.environ

CORS_ORIGIN_ALLOW_ALL = False
CORS_ALLOW_CREDENTIALS = True

DEBUG = environment.get('DEBUG')

SECRET_KEY = environment.get('SECRET_KEY')

ALLOWED_HOSTS = [environment.get('ALLOWED_HOSTS')]
CORS_ORIGIN_WHITELIST = environment.get('ALLOWED_ORIGINS').split(',')

if DEBUG:
    import mimetypes
    mimetypes.add_type("application/javascript", ".js", True)

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases


DATABASES = {
    'default': dj_database_url.parse(
        environment.get('DATABASE_URL'), conn_max_age=600)
}

SPLITTED_CLOUDINARY_URL = environment.get('CLOUDINARY_URL').split(':')

CLOUDINARY = {
    'cloud_name': SPLITTED_CLOUDINARY_URL[2].split('@')[1],
    'api_key': SPLITTED_CLOUDINARY_URL[1][2:],
    'api_secret': SPLITTED_CLOUDINARY_URL[2].split('@')[0],
}

# CACHES = {
#     "default": {
#         "BACKEND": "django_redis.cache.RedisCache",
#         "LOCATION": environment.get('REDIS_URL'),
#         "OPTIONS": {
#             "CLIENT_CLASS": "django_redis.client.DefaultClient"
#         }
#     }
# }

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=int(environment.get('ACCESS_TOKEN_EXPIRATION_TIME'))),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=int(environment.get('REFRESH_TOKEN_EXPIRATION_TIME'))),
    'UPDATE_LAST_LOGIN': True,
}


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Extra places for collectstatic to find static files.
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST = "smtp.gmail.com"
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST_USER = environment.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = environment.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
