# Generated by Django 4.0 on 2022-01-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0004_specification_microbot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
