# Generated by Django 4.0 on 2022-01-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_alter_entry_value'),
        ('automation', '0006_alter_configuration_gitremoterepo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='gitRemoteRepo',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='gitRemoteToken',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='microbotDetailsFileName',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='microbotReadmeFileName',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='specificationDetailsFileName',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='specificationReadmeFileName',
        ),
        migrations.AddField(
            model_name='configuration',
            name='entries',
            field=models.ManyToManyField(blank=True, related_name='microbot_outputs', to='configuration.Entry'),
        ),
    ]
