# Generated by Django 4.0 on 2022-01-03 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_birth_date'),
        ('automation', '0007_remove_configuration_gitremoterepo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
