# Generated by Django 4.0 on 2022-01-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_entry_user'),
        ('automation', '0008_alter_configuration_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='entries',
            field=models.ManyToManyField(blank=True, to='configuration.Entry'),
        ),
    ]
