version: '3.8'
services:
  backend:
    build: ./backend/
    ports:
      - '8081:8000'
    command: hypercorn robofi.handlers.asgi:application --bind 0.0.0.0:8000
    container_name: robofi-backend

  frontend:
    build: ./frontend/
    ports:
      - '80:80'
    command: node server.js
    container_name: robofi-frontend
