# Generated by Django 4.0 on 2022-01-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='value',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
