# Generated by Django 4.0 on 2021-12-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(db_index=True, max_length=120, null=True)),
                ('Email', models.CharField(max_length=50, null=True)),
                ('Contact', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(db_index=True, max_length=120, null=True)),
                ('Type', models.CharField(max_length=50, null=True)),
                ('Description', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Message', models.CharField(db_index=True, max_length=120, null=True)),
                ('Code', models.CharField(db_index=True, max_length=50, null=True)),
                ('Description', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(db_index=True, max_length=120, null=True)),
                ('Type', models.CharField(max_length=50, null=True)),
                ('DefaultValue', models.CharField(max_length=120, null=True)),
                ('Description', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(db_index=True, max_length=120, null=True)),
                ('Type', models.CharField(max_length=50, null=True)),
                ('Description', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(db_index=True, max_length=120)),
                ('Description', models.CharField(blank=True, max_length=300, null=True)),
                ('Category', models.CharField(db_index=True, max_length=50)),
                ('Version', models.CharField(db_index=True, default='1.0.0', max_length=20)),
                ('Authors', models.ManyToManyField(blank=True, related_name='microbot_authors', to='specification.Author')),
                ('Dependencies', models.ManyToManyField(blank=True, related_name='microbot_dependencies', to='specification.Dependency')),
                ('Errors', models.ManyToManyField(blank=True, related_name='microbot_errors', to='specification.Error')),
                ('Inputs', models.ManyToManyField(blank=True, related_name='microbot_inputs', to='specification.Input')),
                ('Outputs', models.ManyToManyField(blank=True, related_name='microbot_outputs', to='specification.Output')),
            ],
        ),
    ]
