# Generated by Django 4.0 on 2021-12-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='error',
            name='Description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
