# Generated by Django 4.0 on 2022-01-01 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microbot', '0002_delete_microbot'),
        ('specification', '0002_alter_error_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Specification',
        ),
    ]
