# Generated by Django 4.0 on 2022-01-01 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0003_delete_specification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dependency',
            options={'verbose_name_plural': 'dependencies'},
        ),
    ]
