# Generated by Django 4.0 on 2021-12-19 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('specification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Microbot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(db_index=True, max_length=120)),
                ('Technology', models.CharField(db_index=True, max_length=25)),
                ('Description', models.CharField(blank=True, max_length=300, null=True)),
                ('Version', models.CharField(db_index=True, default='1.0.0', max_length=20)),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specification.specification')),
            ],
        ),
    ]
