# Generated by Django 3.2.8 on 2021-11-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(db_index=True, max_length=120, null=True)),
                ('Email', models.CharField(max_length=50, null=True)),
                ('Contact', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(db_index=True, max_length=120, null=True)),
                ('Type', models.CharField(max_length=50, null=True)),
                ('Description', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(db_index=True, max_length=120, null=True)),
                ('Type', models.CharField(max_length=50, null=True)),
                ('DefaultValue', models.CharField(max_length=120, null=True)),
                ('Description', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(db_index=True, max_length=120, null=True)),
                ('Type', models.CharField(max_length=50, null=True)),
                ('Description', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Microbot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(db_index=True, max_length=120, null=True)),
                ('Description', models.CharField(blank=True, max_length=300, null=True)),
                ('Category', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('Version', models.CharField(blank=True, max_length=20, null=True)),
                ('Authors', models.ManyToManyField(null=True, to='automation.Author')),
                ('Dependencies', models.ManyToManyField(null=True, to='automation.Dependency')),
                ('Inputs', models.ManyToManyField(null=True, to='automation.Input')),
                ('Outputs', models.ManyToManyField(null=True, to='automation.Output')),
            ],
        ),
    ]
