# Generated by Django 4.0 on 2022-01-01 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_author_dependency_error_input_output_specification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='microbot',
            name='specification',
        ),
        migrations.RemoveField(
            model_name='specification',
            name='Authors',
        ),
        migrations.RemoveField(
            model_name='specification',
            name='Dependencies',
        ),
        migrations.RemoveField(
            model_name='specification',
            name='Errors',
        ),
        migrations.RemoveField(
            model_name='specification',
            name='Inputs',
        ),
        migrations.RemoveField(
            model_name='specification',
            name='Outputs',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Dependency',
        ),
        migrations.DeleteModel(
            name='Error',
        ),
        migrations.DeleteModel(
            name='Input',
        ),
        migrations.DeleteModel(
            name='Microbot',
        ),
        migrations.DeleteModel(
            name='Output',
        ),
        migrations.DeleteModel(
            name='Specification',
        ),
    ]
