# Generated by Django 4.0 on 2022-01-01 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0003_delete_specification'),
        ('automation', '0003_remove_microbot_specification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(db_index=True, max_length=120)),
                ('Description', models.CharField(blank=True, max_length=300, null=True)),
                ('Category', models.CharField(db_index=True, max_length=50)),
                ('Version', models.CharField(db_index=True, default='1.0.0', max_length=20)),
                ('Authors', models.ManyToManyField(blank=True, related_name='microbot_authors', to='specification.Author')),
                ('Dependencies', models.ManyToManyField(blank=True, related_name='microbot_dependencies', to='specification.Dependency')),
                ('Errors', models.ManyToManyField(blank=True, related_name='microbot_errors', to='specification.Error')),
                ('Inputs', models.ManyToManyField(blank=True, related_name='microbot_inputs', to='specification.Input')),
                ('Outputs', models.ManyToManyField(blank=True, related_name='microbot_outputs', to='specification.Output')),
            ],
        ),
        migrations.CreateModel(
            name='Microbot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(db_index=True, max_length=120)),
                ('Technology', models.CharField(db_index=True, max_length=25)),
                ('Description', models.CharField(blank=True, max_length=300, null=True)),
                ('Version', models.CharField(db_index=True, default='1.0.0', max_length=20)),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automation.specification')),
            ],
        ),
    ]
