# Generated by Django 3.2.8 on 2021-11-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0003_auto_20211127_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='microbot',
            name='Technology',
            field=models.CharField(db_index=True, default='', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='microbot',
            name='Category',
            field=models.CharField(db_index=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='microbot',
            name='Name',
            field=models.CharField(db_index=True, default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='microbot',
            name='Version',
            field=models.CharField(default='1.0.0', max_length=20),
        ),
    ]
