# Generated by Django 3.2.8 on 2021-11-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0004_auto_20211127_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microbot',
            name='Version',
            field=models.CharField(db_index=True, default='1.0.0', max_length=20),
        ),
    ]
