# Generated by Django 4.0 on 2022-01-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0005_alter_configuration_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='gitRemoteRepo',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='gitRemoteToken',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='microbotDetailsFileName',
            field=models.CharField(default='Details.json', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='microbotReadmeFileName',
            field=models.CharField(default='README.md', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='specificationDetailsFileName',
            field=models.CharField(default='Details.json', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='specificationReadmeFileName',
            field=models.CharField(default='README.md', max_length=300, null=True),
        ),
    ]
