# Generated by Django 3.2.8 on 2021-12-12 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0005_alter_microbot_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Message', models.CharField(db_index=True, max_length=120, null=True)),
                ('Code', models.CharField(db_index=True, max_length=50, null=True)),
                ('Description', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='microbot',
            name='Authors',
        ),
        migrations.RemoveField(
            model_name='microbot',
            name='Category',
        ),
        migrations.RemoveField(
            model_name='microbot',
            name='Dependencies',
        ),
        migrations.RemoveField(
            model_name='microbot',
            name='Inputs',
        ),
        migrations.RemoveField(
            model_name='microbot',
            name='Outputs',
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(db_index=True, max_length=120)),
                ('Description', models.CharField(blank=True, max_length=300, null=True)),
                ('Category', models.CharField(db_index=True, max_length=50)),
                ('Version', models.CharField(db_index=True, default='1.0.0', max_length=20)),
                ('Authors', models.ManyToManyField(blank=True, related_name='microbot_authors', to='automation.Author')),
                ('Dependencies', models.ManyToManyField(blank=True, related_name='microbot_dependencies', to='automation.Dependency')),
                ('Errors', models.ManyToManyField(blank=True, related_name='microbot_errors', to='automation.Error')),
                ('Inputs', models.ManyToManyField(blank=True, related_name='microbot_inputs', to='automation.Input')),
                ('Outputs', models.ManyToManyField(blank=True, related_name='microbot_outputs', to='automation.Output')),
            ],
        ),
        migrations.AddField(
            model_name='microbot',
            name='specification',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='automation.specification'),
            preserve_default=False,
        ),
    ]
