name: Docker Image CI - Backend

on:
  push:
    branches: ['main']

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build the Docker image
        run: cd backend && docker build . --file Dockerfile --tag ankitmishraedu/robofi-backend:latest
