name: Publish Docker Image CI

on:
  push:
    branches: ['main']

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - uses: actions/checkout@v3

      - name: Build the Docker image
        run: cd backend && docker build . --file Dockerfile --tag ankitmishraedu/robofi-backend:latest

      - name: Publish Docker image
        run: docker push ankitmishraedu/robofi-backend:latest
